### ISSUE TITLE
Add logging and error handling

### ISSUE THREAD

**Issue by vitkoma** [cngroupdk/locator#6]
Logging - SpringBoot by default supports Sjl4j + logback, so you can use that.
Controllers should return correct HTTP code in case of an error (e.g. 404 if an employee is not found).

**Comment by vicisac** [comment]
Changes Done: Added Error handling and logging to the services classes.

**Comment by vitkoma** [comment]
One more detail: It is a good practice too have a separate logger for every class, so you can later configure different logging for a particular class if needed.

**Comment by vicisac** [comment]
Hi,

Changes done:
- Created a different exception class for each service.
