### ISSUE TITLE
Simplify the code

### ISSUE THREAD

**Issue by vitkoma** [cngroupdk/locator#8]
Keep in mind that other developers will have to understand your code. 
- The Factory pattern is unnecessary here, especially for rooms and floors. Moreover, you actually use Factory Method pattern here and in that case the class should not be named ...Factory
- It is not necessary to convert Iterables to Lists in controllers. You can work directly with iterables. In StaffMemberRepository.getSingleEmployee() you are even converting from List to List.

**Comment by vicisac** [comment]
Changes done: 
- Renamed StaffMemberFactory to StaffMemberCreate
- Removed Factory pattern from Floor, Room and Building.
- Used Iterables directly 
- Removed redundant List processing.

**Comment by vitkoma** [comment]
Please, also remove those `URLDecoder.decode(floor_name, "UTF-8")` lines, the variables are decoded by Spring framework.

Btw. I would call StaffMemberCreate probably AbstractStaffMember, but it's up to you.

**Comment by vicisac** [comment]
Hi,

Changes done:
- I have removed the URLDecoder 
- I removed the Factory for the StaffMembers since it was introducing complexities in other functions.
